<?php

namespace SiteBundle\Repository;

/**
 * User_masterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class User_masterRepository extends \Doctrine\ORM\EntityRepository
{
}
